# Generated by Django 3.0.5 on 2020-04-07 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nic', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('address', models.TextField()),
                ('travel_history', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
